config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/secret_page', to: 'static_pages#secret_page'
  get '/help', to: 'static_pages#help', as: 'help'
  get '/about', to: 'static_pages#about', as: 'about'
  get '/contact', to: 'static_pages#contact', as: 'contact'
  
  resources :users

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: {message: "Rentrez une adresse email valide de moins de 255 caractères."}, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX, message: "Format d'email invalide" },
                    uniqueness: { case_sensitive: false }

  has_secure_password validations: false #This way we can custom validations
  validates :password, presence: true,
                       confirmation: {message: "Les mots de passe ne correspondent pas"},
                       length: { in: 6..40, message: "Rentrez un mot de passe entre 6 et 40 caractères" }
  # Everything below is for the cookies
  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    # remember_token is an instance variable
    # create a new token and add it to the User object
    self.remember_token = User.new_token
    # create a digest from this token and write it in the database
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    # verify is the remember_token correspond to the hash stored in the db
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  add_flash_types :success, :danger #adding flashes besides those already included in rails
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    # create a new session
    # first get the user
    user = User.find_by(email: params[:session][:email].downcase)
    # if user isn't nil and if the password is correct
    if user && user.authenticate(params[:session][:password])
      # log_in (go to sessions_helper)
      log_in user
      # Si la case dans la view est cochée on remember le user, sinon on le forget
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      # remember user by making a cookie (go to sessions_helper)
      # create a token and assign it to the user
      # then create a new cookie with the user id and its tokken
      remember user
      redirect_to "/secret_page", flash: {success: 'Connecté !'}
    else
      redirect_to "/login", flash: { danger: 'Mauvaise combinaison email/mot de passe. Essayez de nouveau'}
    end
  end

  def destroy
    log_out
    redirect_to root_url, flash: { success: "Déconnecté !" }
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end

  def secret_page
    if logged_in?
      # then stay on secret_page
    else
      # else redirection to the login page with a beautiful flash
      redirect_to "/login", flash: { flash: "hey login-toi pour y accéder" }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end


  def create
    @user = User.new(user_params)
    if @user.save
      # Handle a successful save.
      redirect_to("/users/" + @user.id.to_s)
      flash.now[:success] = "Profil utilisateur créé"
      log_in @user
    else
      render 'new'
      # i don't think this flash[:fail] is used
      flash.now[:fail] = "Passwords doesn't match or too short "
    end
  end


  private
  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end

  def edit
    @user = current_user
    # if no user logged
    if @user == nil
      redirect_to login_path
    # go to edit page
    elsif @user.id == params[:id].to_i
    # else case are wrong users
    else
      redirect_to login_path
    end
  end

  def delete
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    # if a temporary already exist
    if (user_id = session[:user_id])
      # 
      @current_user ||= User.find_by(id: user_id)
    # else verify if a cookie exist 
    elsif (user_id = cookies.signed[:user_id])
      # get the user from the id
      user = User.find_by(id: user_id)
      # verify if the user exist and its cookie tokken match with the db
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end

  end

  def remember(user)
    # go to user model for more help
    # create a new cookie token and affect it to the user
    user.remember
    # asign the user.id to the cookie
    cookies.permanent.signed[:user_id] = user.id
    # asign the user's cookie token to the actuel cookie
    cookies.permanent[:remember_token] = user.remember_token
  end

  def logged_in?
    !current_user.nil?
  end
  # Logs out the current user.
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  # Forgets a persistent session.
  def forget(user)
    # delete user's cookie token from the db
    user.forget
    # delete the cookie
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      Le formulaire contient <%= pluralize(@user.errors.count, "erreur") %>.
    </div>
    <ul>
    <% @user.errors.values.each do |msg| %>
      <li><%= msg.first %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Accueil", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "A propos" , about_path %></li>
        <li><%= link_to "Contact" , contact_path %></li>
        <li><%= link_to "Aide", help_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", '#' %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <title>Secret</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>

app/views/static_pages/about.html.erb
<h1>A propos</h1>
<br>
<p>On a créé cette app pour THP</p>

app/views/static_pages/contact.html.erb
<h1>Contact</h1>
<br>
<p>Go sur Slack !</p>

app/views/static_pages/help.html.erb
<h1>Aide</h1>
<p>On peut t'aider via Slack.</p>

app/views/static_pages/home.html.erb
<% # idem que dans la view sessions#new %>
<% if flash.to_h.has_key?('success') %>
<div class="alert alert-success" role="alert">
<%= flash[:success] %>
</div>
<% else end %>
<br>
<h1>Bienvenue sur notre app top-secrète</h1>

<p>Si tu veux connaître le contenu top-secret, il va falloir <a href="/users/new">t'inscrire</a></p>
<br>
<p><a href="/secret_page">La page top secrète</a></p>

app/views/static_pages/secret_page.html.erb
<% # idem que dans la view sessions#new %>
<% if flash.to_h.has_key?('success') %>
<div class="alert alert-success" role="alert">
<%= flash[:success] %>
</div>
<% else end %>
<html>
<p>La réponse à la question de l'univers est : 42 !</p><br>
<marquee>42</marquee><br><br>
<marquee>42</marquee><br><br>
<marquee>42</marquee><br><br>
<marquee>42</marquee><br><br>
<marquee>42</marquee><br><br>
<marquee>42</marquee><br><br>
<marquee>42</marquee><br><br>
</html>

app/views/users/edit.html.erb
<h1>Edit page</h1>

app/views/users/new.html.erb
<html>
  <body>
  <% provide(:title, 'Sign up') %>
    <h1>Créer un compte</h1>
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
                                  <%= render 'layouts/error_messages' %>
        <%= form_for(@user) do |f| %>
          <%= f.label :email %>
          <br>
          <%= f.email_field :email, placeholder: "exemple@exemple.com" , class: 'form-control'%>
          <small>Max 255 caractères</small>
          <br>
          <%= f.label :password %>
          <br>
          <%= f.password_field :password, placeholder: "Mot de passe" , class: 'form-control'%>
          <small>Entre 6 et 40 caractères</small>
          <br>
          <%= f.label :password_confirmation, "Confirmation" %>
          <br>
          <%= f.password_field :password_confirmation, placeholder: "Confirmer mot de passe" , class: 'form-control'%>
          <small>Les mots de passe doivent correspondre</small>
          <br>
          <br>
          <%= f.submit "Créer mon compte", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </body>
</html>

app/views/users/show.html.erb
<%= @user.email %>